### Review Previous Questions

#### 1.Data Types & Basics

Q1: How do you check the data type of a variable?

In [2]:
num = [1,2,3,4,5]

In [3]:
print(type(num))

<class 'list'>


Q2: What are the 4 core Python data types you listed?

In [ ]:
int, float, str, bool, list, tuple, set, dict

#### 2. Lists - Creation & Access

Q3: How do you create a list? "Liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89

In [ ]:
name_height = ["Liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]

In [6]:
print(type(name_height))

<class 'list'>


Q4: How do you access the first element?

In [7]:
name_height[0]

'Liz'

Q5: How do you access the last element?

In [8]:
name_height[-1]

1.89

Q6: How do you slice a list from index i to j?

In [9]:
## slice second to third
name_height[1:3]

[1.73, 'emma']

Q7: Is slicing inclusive or exclusive?

In [ ]:
left inclusive, right exclusive

#### 3. Lists - Modification

Q8: How do you add an item to the end of a list? two ways, add items at the end

In [15]:
 name_height+=["Ting"]

In [17]:
name_height.append(1.62)

In [18]:
name_height

['Liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'Ting', 1.62]

Q9: How do you insert an item at a specific index?

In [19]:
name_height.insert(2, "Tim")

In [20]:
name_height

['Liz', 1.73, 'Tim', 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'Ting', 1.62]

In [21]:
name_height.insert(3,1.70)

In [22]:
name_height

['Liz', 1.73, 'Tim', 1.7, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'Ting', 1.62]

Q10: How do you combine two lists?

In [23]:
additonal_name_height = ["Aurora", 1.75]

In [24]:
name_height + additonal_name_height 

['Liz',
 1.73,
 'Tim',
 1.7,
 'emma',
 1.68,
 'mom',
 1.71,
 'dad',
 1.89,
 'Ting',
 1.62,
 'Aurora',
 1.75]

#### 4.Lists - Removing Elements

Q11: How do you remove an item by value?

In [52]:
name_height.remove("Tim")

ValueError: list.remove(x): x not in list

In [ ]:
name_height

['Liz', 1.73, 1.7, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'Ting', 1.62]

Q12: What does remove() return?

it does not return anything

Q13: How do you remove and return the last element?

In [ ]:
name_height.pop()

1.62

Q14: How do you remove an item by index?

In [ ]:
del name_height[2]

In [ ]:
name_height

['Liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'Ting']

what does del fam[2] do?

it removes the value based on the index value provided but also no value return

Q15: How do you remove and return an element at index i?

In [ ]:
name_height.pop(3)

1.68

Q16: What's the difference between remove() and pop()?

remove by value and no return value, pop() return value index is optional

remove by actual value but pop with index number

#### Lists - Copying (very important)

Q17: What happens with y = x?

y and x bond together if change of x will impact the value in y as well

Q18: How do you create a copy using slicing?

In [41]:
copy_name_height = name_height[:]

In [42]:
copy_name_height

['Liz', 1.73, 'emma', 'mom', 1.71, 'dad', 1.89, 'Ting']

Q19: How do you create a copy using a method?

y= x.copy()

Q20: How do you create a copy using constructor?

y = list(x)

Q21: Additional List question

Which of these is a valid Python list?
- (1,2,3)
- {'a':1}
- [1, 'hello', 1.73]
- {1,2,3}

Q22: Given fam = ['Liz', 1.73, 'emma', 1.68, 'mom', 1.71], what does fam[2] return?


Q23: List Indexing
What does fam.index('mom') return if 'mom' is at position 4?

Q24: What does fam.count(1.73) do?

### Lists - Sorting

Q25: How do you sort a list in-place?

In [44]:
height_only = [1.5, 1.8, 1.62, 1.73, 1.68, 1.71, 1.89, 1.70, 1.75]

In [45]:
height_only.sort()

In [46]:
height_only

[1.5, 1.62, 1.68, 1.7, 1.71, 1.73, 1.75, 1.8, 1.89]

Q26: How do you reverse the list in-place?

In [48]:
height_only.reverse()

In [49]:
height_only

[1.89, 1.8, 1.75, 1.73, 1.71, 1.7, 1.68, 1.62, 1.5]

Q27: How do you remove All items from a list?

Q28: How do you remove  the first occurrence of value 'a' from a list?

### Strings

Q29: What does 'a,b,c'.split(',') return?

Q30: What does ','.join(['a','b']) return?

'a,b'

Q31: What does 'hello'.find('l') return?

Q32: If you're filtering a list of filenames to find CSVs from a specific project, starting with a name of 'JD27' what function would you use to check if the filename starts with 'JD27'? and if the file endswith '.csv'

Q33: Summary the difference between .remove(), .pop(), and del?

Q34: How do you import NumPy with the standard alias?

Q35: What does np_height[:, 1:3] select?

Q36: What is the result of np.logical_not(np.array([0.0, 0.1, -2.5]))?

Q37: How do you generate pseudo-random numbers in NumPy?


np.random.rand() or np.random.random() generates pseudo-random numbers. Use np.random.seed(123) for reproducibility.

Q38: What does np.random.randint(0, 2) generate?

Q39: How to check if a key exist in a dictionary?

Use 'key' in dictionary — returns True or False.

Q40: What does d.get('name', 'unknown') return?

.get(key, default) returns the value for the key, or the default value if the key is not found.

Q41: What does d.keys() return?

Q42: What does d.items() return?

Q43: What does d.pop('age') do?

Q44: How do you update multiple keys at once in a dictionary?

d.update({...}) updates the dictionary with another dictionary or key-value pairs — useful for bulk updates.

Q45: How do you select a single column from a DataFrame as a Series?

brics['country'] returns a Pandas Series. brics[['country']] returns a DataFrame.

Q46: What does df.drop_duplicates() do?

Q47: What does df.sort_values('col', ascending=False) do?

Q48: How do you subset rows where height is over 50?

Q49: What does df.agg({'A':'sum','B':'mean'}) do?

Q50: What does df.cumsum() do?

Q51: In a while loop, when does the code block execute?

Q52: What does a for loop do?

Q53: What is enumerate(seq) used for?

enumerate(iterable, start=0) loops over a sequence keeping track of the index. Returns (index, value) pairs.

Q54: How do you loop over a dictionary's key-value pairs?

Q55: What is the operator for 'strictly less than'?

Q56: How do you import matplotlib for plotting?

Q57: Which function creates a basic line graph?

plt.plot(x, y) creates a line graph. Follow with plt.show() to display.

Q58: Which function creates a scatter plot?

Q59: How do you create a histogram with 3 bins?

Q60: Which function adds a label to the x-axis?